Default: &defaults
  database: astremp.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: astremp_test.sqlite3
  <<: *defaults

Staging:
  database: astremp_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: astremp_production.sqlite3
  poolsize: 100
  <<: *defaults
